version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-app2
    ports:
      - "8000:8000"
    networks:
      - app-network 
    volumes:
      - ./backend:/app # Bind mount your code for live updates

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app2
    ports:
      - "3000:5173"
    environment:
      - VITE_BACKEND_URL=http://django-app:8000
    networks:
      - app-network
    volumes:
      - ./frontend/vite-project:/app/vite-project
      - /app/vite-project/node_modules

 

networks:
  app-network:
    driver: bridge
